// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using llmmo.Data;

#nullable disable

namespace llmmo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614000000_AddTroopsAttacksReports")]
    public partial class AddTroopsAttacksReports
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
