// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using llmmo.Data;

#nullable disable

namespace llmmo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620140000_AddDiplomacy")]
    partial class AddDiplomacy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
